version: "2.2"
services:
  # coypu_demo:
  #   image: akhileshvyas/coypu_demo:latest
  #   hostname: coypu_demo
  #   container_name: coypu_demo
  #   domainname: coypu_demo
  #   volumes:
  #     - ./data:/coypu_demo/data
  #     - ./data_gen:/coypu_demo/data_gen
  #   networks:
  #     - coypu_network

  easyrml:
    image: sdmtib/easyrml:2.0
    hostname: coypu_demo_easyrml
    container_name: coypu_demo_easyrml
    domainname: coypu_demo
    volumes:
      - ./knowledge_graph/kg_creation/easyRML:/easyRML/sources/
    ports:
      - "5000:5000"
    networks:
      - coypu_network

  semantic-enrichment:
    image: asakor/sdmrdfizier:4.0.1
    hostname: coypu_demo_semantic-enrichment
    container_name: coypu_demo_semantic_enrichment
    domainname: coypu_demo
    volumes:
      - ./data:/data/
      - ./knowledge_graph/kg_creation/:/knowledge_graph/kg_creation/
      - ./data_gen/graphs/concepts/:/data_gen/graphs/concepts/
    ports:
      - "4000:4000"
    networks:
      - coypu_network

  dragoman:
    image: sdmtib/dragoman:1.0
    hostname: coypu_demo_dragoman
    container_name: coypu_demo_dragoman
    domainname: coypu_demo
    volumes:
      - ./data:/data
      - ./knowledge_graph/kg_creation/:/knowledge_graph/kg_creation/
      - ./data_gen/graphs/concepts/:/data_gen/graphs/concepts/
      - ./src/mappings_and_config/configs_func/dragoman_func/:/src/mappings_and_config/configs_func/dragoman_func/
    ports:
      - "6000:4000"
    networks:
      - coypu_network

  graphdb:
    # image: ontotext/graphdb:9.3.0-ee
    image: khaller/graphdb-free:latest
    hostname: coypu_demo_graphdb
    container_name: coypu_demo_graphdb
    domainname: coypu_demo
    restart: unless-stopped
    volumes:
      - ./graphdb-home:/opt/graphdb/data/
    ports:
      - 7200:7200
    networks:
      - coypu_network

  # #  dashbaord:
  valsparql:
    # build: ./code/ # Not
    image: valsparql
    hostname: coypu_demo_valsparql
    container_name: coypu_demo_valsparql
    domainname: coypu_demo
    volumes:
      - ./knowledge_graph/kg_validation/api_configs/:/inputs/api_configs/
      - .knowledge_graph/kg_validation/all_shapes/:/inputs/shapes/
    mem_limit: 8g
    ports:
      - '5001:5000'
    networks:
      - coypu_network
  lubm:
    image: prohde/virtuoso-opensource-7:7.2.6-alpine
    hostname: coypu_demo_lubm
    container_name: coypu_demo_lubm
    domainname: coypu_demo
    volumes:
      - ./data_gen/graphs/all_graphs:/database/toLoad
    ports:
      - '15000:8890'
    networks:
      - coypu_network
  #   graphdb:
  #     image: sdmtib/graphdb:9.8.1-free
  #     hostname: coypu_demo_graphdb
  #     container_name: coypu_demo_graphdb
  #     domainname: coypu_demo
  #     volumes:
  #       - ./data_gen:/coypu_demo/data_gen/
  #     ports:
  #       - "7200:7200"
  #     networks:
  #       - coypu_network

networks:
  coypu_network:
    external: true
